const body=document.body;const teacher=document.querySelector('#teacherToggle');
teacher?.addEventListener('click',()=>{const on=body.classList.toggle('teacher-on');teacher.setAttribute('aria-pressed',String(on));teacher.textContent=on?'Exit teacher mode':'Teacher mode'});
document.querySelectorAll('.reveal-btn').forEach(btn=>btn.addEventListener('click',()=>{const card=btn.closest('.gallery-card');const open=card.classList.toggle('open');btn.textContent=open?'Hide reading':'Reveal a possible reading'}));
const storageKey='mm12-w01-decode-the-impossible-progress';let progress={};try{progress=JSON.parse(localStorage.getItem(storageKey)||'{}')}catch{};
document.querySelectorAll('[data-day-check]').forEach(box=>{box.checked=Boolean(progress[box.dataset.dayCheck]);box.addEventListener('change',()=>{progress[box.dataset.dayCheck]=box.checked;localStorage.setItem(storageKey,JSON.stringify(progress))})});
document.querySelectorAll('[data-save]').forEach(field=>{field.value=localStorage.getItem(field.dataset.save)||'';field.addEventListener('input',()=>localStorage.setItem(field.dataset.save,field.value))});
document.querySelector('#quizForm')?.addEventListener('submit',event=>{event.preventDefault();let score=0;const questions=[...document.querySelectorAll('.question')];questions.forEach(q=>{const chosen=q.querySelector('input:checked');const correct=chosen&&Number(chosen.value)===Number(q.dataset.answer);if(correct)score++;q.style.borderColor=correct?'var(--accent)':'var(--danger)'});document.querySelector('#quizResult').innerHTML='<b>'+score+'/'+questions.length+'</b> · '+(score===questions.length?'Explain one answer to a partner.':score>=3?'Review the missed explanations and try again.':'Return to the lab and daily checkpoints before retrying.')});
document.querySelector('#showAnswers')?.addEventListener('click',()=>body.classList.toggle('show-answers'));
const bar=document.querySelector('#progressBar');addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;bar.style.width=(max?scrollY/max*100:0)+'%'},{passive:true});
