/* Operation 7 HTML player v2. No server, learner identity or achievement writes. */
const D=window.O7_DECK,$=id=>document.getElementById(id),answers=new Map(),choices=new Map();
let index=0,stage=0,utterance=null,paused=false,speechToken=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function stopSpeech(){speechToken++;if(window.speechSynthesis?.cancel)window.speechSynthesis.cancel();utterance=null;paused=false;$('audio-status').textContent='';$('pause').textContent='Pause';$('pause').disabled=true;}
function stages(){document.querySelectorAll('[data-stage]').forEach(x=>x.classList.toggle('on',Number(x.dataset.stage)<=stage));$('reveal').hidden=!D.slides[index].stages;$('reveal').disabled=stage>=(D.slides[index].stages||0);$('reveal').textContent='Reveal next stage';}
function render(){stopSpeech();stage=0;const s=D.slides[index];$('position').textContent=`${index+1} / ${D.slides.length}`;$('jump').value=index;$('progress-fill').style.width=`${(index+1)/D.slides.length*100}%`;
$('slide').innerHTML=`<p class="eyebrow">${esc(s.phase)} · ${esc(s.minutes)} MIN · SLIDE ${index+1}</p><h1 class="slide-title">${esc(s.title)}</h1><p class="lead">${esc(s.lead)}</p><div class="layout"><section class="visual" aria-label="${esc(s.visual_alt||'Instructional diagram')}">${s.visual}</section><aside class="side"><h2>Make the connection</h2><p>${esc(s.connection)}</p><div class="question"><h2>Your turn</h2><p>${esc(s.task)}</p><div class="task-meta">${esc(s.roles||'Individual')} · ${esc(s.task_minutes||1)} min</div><p class="vis-caption">Success: ${esc(s.success)}</p></div></aside></div>${s.check?`<div class="check-options" aria-label="Practice choices">${s.check.options.map((o,i)=>`<button type="button" data-option="${i}">${esc(o)}</button>`).join('')}</div><p id="feedback" class="feedback" role="status"></p>`:''}<div class="response"><label for="answer">${esc(s.response_label||'Write or sketch on paper; use this box if helpful')}</label><textarea id="answer"></textarea><small>Practice only. Responses stay in this tab; download before closing or refreshing.</small></div><details class="transcript"><summary>Read the full narration</summary><p>${esc(s.narration)}</p></details><p class="source">${esc(s.source)}${s.source_url?` <a href="${esc(s.source_url)}" target="_blank" rel="noopener">Read the source ↗</a>`:''}</p>`;
$('answer').value=answers.get(index)||'';$('answer').addEventListener('input',e=>answers.set(index,e.target.value));$('back').disabled=index===0;$('next').disabled=index===D.slides.length-1;stages();
document.querySelectorAll('[data-option]').forEach(b=>b.addEventListener('click',()=>{choices.set(index,Number(b.dataset.option));applyChoice();}));if(choices.has(index))applyChoice();
if(s.widget==='ranking'){const w=$('weight');w.addEventListener('input',rank);$('run-ranking').addEventListener('click',()=>{rank(true);});rank(false);}
history.replaceState(null,'',`#slide-${index+1}`);$('slide').focus({preventScroll:true});window.scrollTo(0,0);}
function applyChoice(){const s=D.slides[index],k=choices.get(index);document.querySelectorAll('[data-option]').forEach(b=>{const chosen=Number(b.dataset.option)===k;b.setAttribute('aria-pressed',String(chosen));b.dataset.result=chosen?(k===s.check.answer?'right':'wrong'):'';});$('feedback').textContent=k===s.check.answer?s.check.correct:s.check.retry;}
function rank(run){const w=Number($('weight').value);$('weight-value').textContent=w;const box=$('ranking-results');if(run!==true){box.innerHTML='<p>Predict the order, then choose Run ranking.</p>';return;}const rows=D.slides[index].rows.map(r=>({...r,score:2*r.relevance+w*r.novelty})).sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id));box.innerHTML=rows.map((r,i)=>`<div class="score-card"><span class="tag">${i+1} · ${esc(r.id)} · ${esc(r.name)}</span><strong>${r.score}</strong><span>2 × ${r.relevance} + ${w} × ${r.novelty}</span><div class="ranking-bar" style="width:${r.score/15*100}%"></div></div>`).join('');}
function go(i){if(i>=0&&i<D.slides.length){index=i;render();}}
$('back').onclick=()=>go(index-1);$('next').onclick=()=>go(index+1);$('jump').onchange=e=>go(Number(e.target.value));$('reveal').onclick=()=>{stage++;stages();};
$('speak').onclick=()=>{stopSpeech();if(typeof window.speechSynthesis?.speak!=='function'){$('audio-status').textContent='Speech unavailable; read the transcript.';return;}const token=speechToken;utterance=new SpeechSynthesisUtterance(D.slides[index].narration);utterance.lang='en-CA';utterance.rate=.94;utterance.onend=()=>{if(token!==speechToken)return;$('audio-status').textContent='Finished this slide.';$('pause').disabled=true;};utterance.onerror=()=>{if(token!==speechToken)return;$('audio-status').textContent='Use the transcript.';$('pause').disabled=true;};$('pause').disabled=false;speechSynthesis.speak(utterance);$('audio-status').textContent='Reading with this device’s voice.';document.querySelector('.transcript').open=true;};
$('pause').onclick=()=>{if(!utterance)return;paused=!paused;if(paused)speechSynthesis.pause();else speechSynthesis.resume();$('pause').textContent=paused?'Resume':'Pause';$('audio-status').textContent=paused?'Paused.':'Reading.';};$('stop').onclick=stopSpeech;
$('present').onclick=()=>{const on=document.body.classList.toggle('presenter');$('present').setAttribute('aria-pressed',String(on));$('present').textContent=on?'Study view':'Classroom view';};
$('download').onclick=()=>{const text=D.title+'\n\n'+D.slides.map((s,i)=>`${i+1}. ${s.title}\n${answers.get(i)||'(no typed response)'}\n`).join('\n');const u=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=u;a.download='MM12-practice-responses.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','BUTTON','A','SELECT','SUMMARY'].includes(document.activeElement?.tagName))return;if(e.key==='ArrowRight')go(index+1);if(e.key==='ArrowLeft')go(index-1);});
$('course').firstChild.textContent=D.course;$('deck-title').textContent=D.title;document.title=D.title+' · Operation 7';$('privacy').textContent=D.privacy||'Practice responses remain in this tab. No uploads or grades.';$('jump').innerHTML=D.slides.map((s,i)=>`<option value="${i}">${i+1}. ${esc(s.title)}</option>`).join('');
const m=location.hash.match(/^#slide-([0-9]+)$/);if(m)index=Math.max(0,Math.min(D.slides.length-1,Number(m[1])-1));render();
